# Generated by Django 4.2 on 2023-05-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['id'], 'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
