# Generated by Django 4.2.1 on 2023-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('author', models.TextField(blank=True, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['id'], 'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AddField(
            model_name='profession',
            name='price',
            field=models.TextField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='human',
            name='Last_name',
            field=models.TextField(blank=True, verbose_name='Портфолио'),
        ),
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='human',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Специализация'),
        ),
    ]
