# Generated by Django 4.2.1 on 2023-06-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_profession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='Last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
    ]
