# Generated by Django 4.2 on 2023-09-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_review_alter_profession_options_profession_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.TextField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(blank=True, verbose_name='Эл. ящик или телефон для обратной связи'),
        ),
    ]
