# Generated by Django 4.2 on 2023-05-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Имя')),
                ('Last_name', models.TextField(blank=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homework.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'людей',
                'verbose_name_plural': 'Люди',
                'ordering': ['id'],
            },
        ),
    ]
